name: PiggyAntiCheats
main: PiggyAntiCheats\Main
version: 1.0.0
api: [3.0.0, 3.0.0-ALPHA12, 4.0.0]
author: DaPigGuy
permissions:
  piggyanticheats:
    default: op
    description: ""
    children:
      piggyanticheats.notify:
        default: op
        description: ""
